name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: "JDK 21 Eclipse Temurin"
    runs-on: ${{ matrix.os }}
#    container: "maven:3.9.6-eclipse-temurin-21"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-jdk17-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-jdk17
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'Build'
        run: |
          mvn \
          --show-version \
          --fail-at-end \
          --batch-mode \
          --no-transfer-progress \
          clean verify \
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./rewrite-testcontainers-gitserver/target/site/jacoco/jacoco.xml, ./testcontainers-gitserver/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: false