name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    name: "JDK 21 Eclipse Temurin Linux"
    runs-on: ubuntu-latest
    container: "maven:3.9.6-eclipse-temurin-21"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-jdk17-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-jdk17
      - name: 'Build'
        run: |
          mvn \
          --show-version \
          --fail-at-end \
          --batch-mode \
          --no-transfer-progress \
          clean verify \
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./rewrite-testcontainers-gitserver/target/site/jacoco/jacoco.xml, ./testcontainers-gitserver/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: false
  windows-build:
    name: "JDK 21 Eclipse Temurin Windows"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-jdk17-windows-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-jdk17
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: 'Build'
        run: |
          mvn 
          --fail-at-end \
          --batch-mode \
          --no-transfer-progress \
          clean verify \